const modal = document.querySelector('#mission-modal');
const modalTitle = document.querySelector('#modal-title');
const modalCopy = document.querySelector('#modal-copy');
const missionCopy = { 'El Conde': 'La primera coordenada está activa. Sigue la señal por la Zona Colonial.', Planeta: 'La ruta global está lista. Prepárate para el salto Santo Domingo → Miami → Tokyo.', Catacumbas: 'Acceso clasificado detectado. Esta ruta requiere acceso total.' };
document.querySelectorAll('.mission-button').forEach((button) => button.addEventListener('click', () => { modalTitle.textContent = button.dataset.mission; modalCopy.textContent = missionCopy[button.dataset.mission]; modal.showModal(); }));
document.querySelector('.close').addEventListener('click', () => modal.close());
const canvas = document.querySelector('#orbit-run-canvas'); const start = document.querySelector('#game-start');
if (canvas && start) { const ctx=canvas.getContext('2d'), scoreNode=document.querySelector('#game-score'), status=document.querySelector('#game-status'), keys=new Set(); let frame, active=false, state;
  const reset=()=>{state={x:360,score:0,signals:[],hazards:[],signalAt:0,hazardAt:0};scoreNode.textContent='0';status.textContent='EN RUTA'};
  const draw=(time)=>{const {width:w,height:h}=canvas;ctx.fillStyle='#071117';ctx.fillRect(0,0,w,h);for(let i=0;i<72;i++){ctx.fillStyle=i%9?'#78919a':'#d8f455';ctx.fillRect((i*97)%w,(i*59+time/28)%h,2,2)}if(keys.has('ArrowLeft')||keys.has('a'))state.x=Math.max(25,state.x-7);if(keys.has('ArrowRight')||keys.has('d'))state.x=Math.min(w-25,state.x+7);if(time-state.signalAt>700){state.signals.push({x:35+Math.random()*(w-70),y:-10});state.signalAt=time}if(time-state.hazardAt>1100){state.hazards.push({x:35+Math.random()*(w-70),y:-20});state.hazardAt=time}state.signals.forEach(x=>x.y+=3.5);state.hazards.forEach(x=>x.y+=4.5);state.signals=state.signals.filter(x=>{if(Math.abs(x.x-state.x)<30&&Math.abs(x.y-(h-43))<30){state.score++;scoreNode.textContent=state.score;return false}return x.y<h+15});const hit=state.hazards.some(x=>Math.abs(x.x-state.x)<32&&Math.abs(x.y-(h-43))<31);state.signals.forEach(x=>{ctx.fillStyle='#d8f455';ctx.beginPath();ctx.arc(x.x,x.y,8,0,7);ctx.fill()});state.hazards.forEach(x=>{ctx.fillStyle='#ff6b4a';ctx.beginPath();ctx.arc(x.x,x.y,14,0,7);ctx.fill()});ctx.fillStyle='#f4f2e9';ctx.beginPath();ctx.moveTo(state.x,h-73);ctx.lineTo(state.x-19,h-24);ctx.lineTo(state.x+19,h-24);ctx.closePath();ctx.fill();if(hit){active=false;status.textContent=`FIN · ${state.score} SEÑALES`;start.innerHTML='Jugar otra vez <b>↗</b>';return}frame=requestAnimationFrame(draw)};
  start.addEventListener('click',()=>{cancelAnimationFrame(frame);active=true;reset();start.innerHTML='Reiniciar demo <b>↗</b>';frame=requestAnimationFrame(draw)});window.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),key=k==='arrowleft'?'ArrowLeft':k==='arrowright'?'ArrowRight':k;if(active&&['ArrowLeft','ArrowRight','a','d'].includes(key)){keys.add(key);e.preventDefault()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()==='arrowleft'?'ArrowLeft':e.key.toLowerCase()==='arrowright'?'ArrowRight':e.key.toLowerCase())); }
