const modal = document.querySelector('#notice-modal');
const title = document.querySelector('#notice-title');
document.querySelectorAll('.notify').forEach((button) => button.addEventListener('click', () => { title.textContent = button.dataset.product; modal.showModal(); }));
document.querySelector('.close-modal').addEventListener('click', () => modal.close());
document.querySelector('.close-notice').addEventListener('click', () => modal.close());
const canvas = document.querySelector('#orbit-run-canvas');
const start = document.querySelector('#game-start');
if (canvas && start) {
  const ctx = canvas.getContext('2d'); const scoreNode = document.querySelector('#game-score'); const status = document.querySelector('#game-status'); const keys = new Set(); let frame; let active = false; let state;
  const reset = () => { state = { x: 360, score: 0, signals: [], hazards: [], signalAt: 0, hazardAt: 0 }; scoreNode.textContent = '0'; status.textContent = 'EN RUTA'; };
  const draw = (time) => { const { width: w, height: h } = canvas; ctx.fillStyle = '#071015'; ctx.fillRect(0, 0, w, h); for (let i = 0; i < 72; i += 1) { ctx.fillStyle = i % 9 ? '#68858a' : '#d9f45a'; ctx.fillRect((i * 97) % w, (i * 59 + time / 28) % h, 2, 2); } if (keys.has('ArrowLeft') || keys.has('a')) state.x = Math.max(25, state.x - 7); if (keys.has('ArrowRight') || keys.has('d')) state.x = Math.min(w - 25, state.x + 7); if (time - state.signalAt > 700) { state.signals.push({ x: 35 + Math.random() * (w - 70), y: -10 }); state.signalAt = time; } if (time - state.hazardAt > 1100) { state.hazards.push({ x: 35 + Math.random() * (w - 70), y: -20 }); state.hazardAt = time; } state.signals.forEach((item) => { item.y += 3.5; }); state.hazards.forEach((item) => { item.y += 4.5; }); state.signals = state.signals.filter((item) => { if (Math.abs(item.x - state.x) < 30 && Math.abs(item.y - (h - 43)) < 30) { state.score += 1; scoreNode.textContent = state.score; return false; } return item.y < h + 15; }); const hit = state.hazards.some((item) => Math.abs(item.x - state.x) < 32 && Math.abs(item.y - (h - 43)) < 31); state.signals.forEach((item) => { ctx.fillStyle = '#d9f45a'; ctx.beginPath(); ctx.arc(item.x, item.y, 8, 0, Math.PI * 2); ctx.fill(); }); state.hazards.forEach((item) => { ctx.fillStyle = '#ff7043'; ctx.beginPath(); ctx.arc(item.x, item.y, 14, 0, Math.PI * 2); ctx.fill(); }); ctx.fillStyle = '#f3f0e7'; ctx.beginPath(); ctx.moveTo(state.x, h - 73); ctx.lineTo(state.x - 19, h - 24); ctx.lineTo(state.x + 19, h - 24); ctx.closePath(); ctx.fill(); if (hit) { active = false; status.textContent = `FIN · ${state.score} SEÑALES`; start.innerHTML = 'Jugar otra vez <b>↗</b>'; return; } frame = requestAnimationFrame(draw); };
  start.addEventListener('click', () => { cancelAnimationFrame(frame); active = true; reset(); start.innerHTML = 'Reiniciar demo <b>↗</b>'; frame = requestAnimationFrame(draw); });
  window.addEventListener('keydown', (event) => { const lower = event.key.toLowerCase(); const key = lower === 'arrowleft' ? 'ArrowLeft' : lower === 'arrowright' ? 'ArrowRight' : lower; if (active && ['ArrowLeft', 'ArrowRight', 'a', 'd'].includes(key)) { keys.add(key); event.preventDefault(); } });
  window.addEventListener('keyup', (event) => { const lower = event.key.toLowerCase(); keys.delete(lower === 'arrowleft' ? 'ArrowLeft' : lower === 'arrowright' ? 'ArrowRight' : lower); });
}
